name: Build and make release on tag

on:
  workflow_dispatch:
  push:
    tags:
    - '*'

permissions:
  actions: read
  contents: write
  packages: write

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run type checking
        run: npm run check-types

      - name: Run all tests
        run: npm test

  build-vsix:
    needs: test
    runs-on: ubuntu-24.04
    steps:

    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
        cache-dependency-path: ./package-lock.json

    - name: Install NPM dependencies
      run: |
          npm install -g @vscode/vsce
          npm install

    - name: Build VSIX
      run: |
          rm -f *.vsix
          npm run package

    - name: Upload VSIX
      uses: actions/upload-artifact@v4
      with:
        name: vscode-arduino-sketch-vault.vsix
        path: vscode-arduino-sketch-vault*.vsix

  make-release:
    needs: build-vsix
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:

    - uses: actions/checkout@v4

    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: .

    - name: Cleaning up VSIX
      run: |
          rev=$(git rev-parse --short HEAD)
          mkdir release
          cp ./vscode-arduino-sketch-vault.vsix/vscode-arduino-sketch-vault-*.vsix ./release/.
          ls -l release

    - name: Drafting release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "release/*"
        draft: true
        generateReleaseNotes: true
